# Generated by Django 5.2.17 on 2026-08-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD')], max_length=20)),
                ('teaching_language', models.CharField(choices=[('ENGLISH', 'English'), ('GERMAN', 'German')], max_length=20)),
                ('semester', models.CharField(choices=[('WINTER', 'Winter'), ('SUMMER', 'Summer')], max_length=20)),
                ('application_start', models.DateField(blank=True, null=True)),
                ('application_end', models.DateField(blank=True, null=True)),
                ('application_platform', models.CharField(choices=[('DIRECT', 'Direct'), ('UNI_ASSIST', 'Uni-Assist')], max_length=20)),
                ('nc_status', models.CharField(choices=[('NC_FREE', 'NC-Free'), ('NC', 'NC')], max_length=10)),
                ('program_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('website', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LanguageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('GERMAN', 'German')], max_length=20)),
                ('exam', models.CharField(choices=[('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('TESTDAF', 'TestDaF'), ('DSH', 'DSH'), ('GOETHE', 'Goethe'), ('TELC', 'telc')], max_length=20)),
                ('minimum_score', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_requirements', to='universities.program')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('minimum_german_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('gre', models.BooleanField(default=False)),
                ('gmat', models.BooleanField(default=False)),
                ('aps_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requirement', to='universities.program')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university'),
        ),
    ]
