# Generated by Django 5.2.17 on 2026-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='vpd_required',
            field=models.BooleanField(default=False),
        ),
    ]
