# Generated by Django 5.2.17 on 2026-09-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='application_platform',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('UNI_ASSIST', 'Uni-Assist'), ('VPD', 'Uni-Assist VPD')], max_length=20),
        ),
    ]
