# Generated by Django 5.2.17 on 2026-09-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_alter_program_application_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionrequirement',
            old_name='minimum_german_gpa',
            new_name='required_german_gpa',
        ),
    ]
