# Generated by Django 5.2.17 on 2026-08-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_program_vpd_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionrequirement',
            name='minimum_gpa',
        ),
    ]
