# Generated by Django 5.2.17 on 2026-09-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_rename_minimum_german_gpa_admissionrequirement_required_german_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagerequirement',
            name='minimum_score',
        ),
        migrations.AddField(
            model_name='languagerequirement',
            name='minimum_level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='languagerequirement',
            name='minimum_score_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
